;;; Uncomment the modules you'd like to use and restart Prelude afterwards

(require 'prelude-ido)
(require 'prelude-programming)
(require 'prelude-clojure)
(require 'prelude-common-lisp)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
(require 'prelude-js)
(require 'prelude-lisp)
(require 'prelude-org)
(require 'prelude-python)
(require 'prelude-ruby)
(require 'prelude-scala)
(require 'prelude-scss)
(require 'prelude-web)
(require 'prelude-xml)
(require 'prelude-yaml)
(require 'prelude-elixir)
